import "./HomePage.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faClone, faDatabase, faUpload, faMagnifyingGlass, faFileLines } from "@fortawesome/free-solid-svg-icons";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../hooks/useAuth";
import Navbar from "../Navbar/Navbar";

const HomePage = () => {
    const navigate = useNavigate();
    const { userId } = useAuth();
    const handleClick = () => {
        if (userId)
            navigate("/profile");
        else
            navigate("/login");
    }
    return (
        <>
            <Navbar />
            <div className="home">
                <h2>Query Your PDFs with ease</h2>
                <h5>Upload you pdfs and start querying with our powerful RAG</h5>
                <button className="btn" onClick={handleClick}>Get Started</button>
                <div className="features">
                    <div className="attr1">
                        <div>
                            <FontAwesomeIcon className="icon" icon={faUpload} style={{ color: "#fafafa" }} />
                            <p>Upload a pdf</p>
                        </div>
                        <div>
                            <FontAwesomeIcon className="icon" icon={faDatabase} style={{ color: "#f5f5f5" }} />
                            <p>Chunked pieces are embedded</p>
                        </div>
                    </div>
                    <div className="attr2">
                        <div>
                            <FontAwesomeIcon className="icon" icon={faClone} />
                            <p>Documents are chunked</p>
                        </div>
                        <div>
                            <FontAwesomeIcon className="icon" icon={faMagnifyingGlass} style={{ color: "#f6f7f9", }} />
                            <p>Similarity Search is done on <br /> user query</p>
                        </div>
                    </div>
                </div>
                <div className="results">
                    <FontAwesomeIcon className="icon" icon={faFileLines} style={{ color: "#f1f2f3", }} />
                    <p>Results are generated by LLM <br /> along with augmented prompt</p>
                </div>
            </div>
        </>
    );
}

export default HomePage;